<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>$(RepoRootPath)assets/hextail-logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="DialogHost.Avalonia" />
    <PackageReference Include="Optris.Icons.Avalonia.MaterialDesign" />
    <PackageReference Include="Polly" />
    <PackageReference Include="GnomeStack.Os.Secrets" />
    <PackageReference Include="ReactiveUI.Avalonia.Reactive" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="Xaml.Behaviors.Interactivity" />
    <PackageReference Include="Xaml.Behaviors.Interactions" />
    <PackageReference Include="Xaml.Behaviors.Interactions.Events" />
  </ItemGroup>
</Project>
